### ISSUE TITLE
Issue with writing data back to stream - data not received by the other side

### ISSUE THREAD

**Issue by xtwist** [cauvmou/tokio-quic#4]
Hello, and first off, thank you for developing such a useful library! It has significantly simplified my workflows. However, I've encountered an issue where data written back to a stream is not being received on the other side.

I'm utilizing Rust to obtain a stream and read-write messages as follows:
```rust
let mut stream = connection.incoming().await.expect("receive connection");
let mut buf: [u8; u16::MAX as usize] = [0; u16::MAX as usize];
let n = stream.read(&mut buf).await.expect("read incoming message");
stream.write_all(b"test message").await.expect("write message back"); // nothing happens on the Go side, getting timeout error
stream.flush().await.expect("flush"); // nothing happens on the Go side, getting timeout error
```
The corresponding bidirectional stream on the other side is established using quic-go, as documented here: [quic-go Connection.OpenStream](https://pkg.go.dev/github.com/lucas-clemente/quic-go#Connection.OpenStream).

Could there be a restriction that streams obtained via _incoming()_ are unidirectional, preventing data from being sent back? Or might there be another explanation for this behavior?

Any insights or suggestions would be greatly appreciated.

**Comment by cauvmou** [comment]
Thank you for bringing this to my attention, I will look into it as soon as I have the time to do so.  As to answer your question, there should be no restriction on incoming streams being unidirectional only. Maybe you could try and inspect your network traffic and look for a response from your rust program. If there is then maybe the Issue is on the go-lang side of things (Although that doesn't really narrow it down all that much), otherwise please be patient.

Do you have a specific go-lang example you could provide me so I can look into it?

**Comment by xtwist** [comment]
@cauvmou Thank you so much for your reply. I will prepare detailed examples this week and let you know the result.

**Comment by cauvmou** [comment]
> @cauvmou Thank you so much for your reply. I will prepare detailed examples this week and let you know the result.

Just wanted to check in, any update on those examples?

**Comment by xtwist** [comment]
@cauvmou I'm still investigating it. It looks like it happens to me when the client and server are connected in the same network (desktop and laptop). I will shortly come up with some code to try.

**Comment by xtwist** [comment]
I figured out that the reason for the strange behavior was my internal protocol implementation. Messages were too short.  Issue can be closed.
